# General settings

# Basis and model parameters
basis_Nx: 20
basis_Ny: 20
filter_frac: 1.0 # 2/3

x_scale: 1.0
y_scale: 1.0

cylinder_x: 0.0
cylinder_y: 0.0
cylinder_radius: 0.1

residual_weights:
  equation: 1.0
  immersed: 1.0
  wall: 1.0
  inlet: 1.0
  outlet: 1.0
  continuity: 1.0

# Sampling parameters
n_pde: 10000
n_bc: 5000
n_immersed: 5000

# Solver settings
solver_type: "FirstOrder"
optimizer_name: "adam"      # <-- Changed from "Adam"
loss_strategy: "Standard"
precondition: True
init: ""
solver_kwargs:
  rtol: 1e-6
  atol: 1e-6
verbose: True
learning_rate: 0.005 # Only used for Adam
max_steps: 5000     # Only used for Adam
n_epochs: 2000     # Only used for Adam

# Data paths
data_dir: "data/"
results_dir: "results/"
