# General settings

# Basis and model parameters
basis_Nx: 50
basis_Ny: 50
filter_frac: 1.0 # 2/3

x_scale: 1.0
y_scale: 1.
nu: 1.0
RE: 400.0

residual_weights:
  equation: 1.0
  wall: 1.0
  inlet: 1.0
  outlet: 1.0
  continuity: 1.0

# Sampling parameters
n_pde: 40000
n_bc: 8000
n_immersed: 5000
n_annulus: 8000
annulus_r: 2.0

# Solver settings
solver_type: "FirstOrder"
optimizer_name: "nadam"      # <-- Changed from "Adam"
loss_strategy: "RegularizedAdaptive"
precondition: True
init: "fitted"
solver_kwargs:
  rtol: 1e-6
  atol: 1e-6
verbose: True
learning_rate: 0.1 # Only used for Adam
max_steps: 1000     # Only used for Adam
n_epochs: 2000     # Only used for Adam
regularization_strength: 0.0000001
grad_clipping: 1000.0

# Data paths
data_dir: "data/"
results_dir: "results/"
