# General settings
alpha: 0.5

basis_Nx: 10
basis_Ny: 10
basis_Nz: 10
basis_Nt: 10
filter_frac: 1.0 # 2/3
residual_weights:
  equation: 1.0
  initial: 1.0

# Sampling parameters
n_pde: 500
n_initial: 4000
n_t: 30

# Solver settings
solver_type: "FirstOrder"
optimizer_name: "adam"      # <-- Changed from "Adam"
loss_strategy: "RegularizedAdaptive"
solver_kwargs:
  rtol: 1e-4
  atol: 1e-4
verbose: True
learning_rate: 0.01 # Only used for Adam
max_steps: 500 
n_epochs: 1000  # Only used for Adam
regularization_strength: 0.0001

# Data paths
results_dir: "results/"