# Basis and model parameters
basis_Nx: 20
basis_Ny: 20
filter_frac: 1.0
trainable: True
experiment_name: "visc_inv_Ross"

# Sampling parameters
n_pde: 10000
n_data: 10000
n_bc: 800

# Physical parameters
rho_i: 917.0
rho_w: 1030.0
g: 9.8

# Solver settings
solver: 'LevenbergMarquardt' # or 'Adam'
solver_kwargs:
  rtol: 1e-6
  atol: 1e-6
residual_weights:
  equation: 10.0
  boundary: 10.0
  reference_data: 100.0
learning_rate: 0.0001
n_epochs: 10000
max_steps: 500
verbose: True

# Data paths
data_path: "data/Ross_data.h5"
results_dir: "results/"